services:
  homelab-dashboard:
    image: ghcr.io/manishboharaa/homelab-dashboard:latest
    container_name: homelab-dashboard
    restart: unless-stopped
    pull_policy: always
    network_mode: host
    environment:
      - PORT=8080
      - TZ=America/New_York
      - HOST_DISK_PATH=/hostfs
    volumes:
      - ./data:/app/data
      - /:/hostfs:ro
      - /sys/class/thermal:/sys/class/thermal:ro
      - /proc:/host/proc:ro
    pid: host
